### ISSUE TITLE
Getting error in MS Learn Exercise

### ISSUE THREAD

**Issue by vp393001** [MicrosoftDocs/mslearn-deploy-run-container-app-service#4]
I'm trying to follow this Exercise: [MS Learn Link](https://docs.microsoft.com/en-in/learn/modules/deploy-run-container-app-service/3-exercise-build-images?pivots=csharp)

Getting following error after running `az acr build` command.

```
Packing source code into tar to upload...
Excluding '.gitignore' based on default ignore rules
Uploading archived source code from '/tmp/build_archive_adf23459b81c4b5aaa02858553804858.tar.gz'...
Sending context (2.152 KiB) to registry: azure234...
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py",line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py",line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py",line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py",line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/build.py", line 109, in acr_build
    variant=platform_variant
TypeError: 'NoneType' object is not callable
To open an issue, please run: 'az feedback'
```

**Comment by AnjaliL** [comment]
This issue is fixed in the latest patch of az cli

Install the latest az cli using curl

`curl -L https://aka.ms/InstallAzureCli | bash`

Reference Link [https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script](url),
[https://github.com/Azure/azure-cli/issues/18963](url)

**Comment by vp393001** [comment]
Hi @AnjaliL, it's working. Thanks!!
